// automatedTests/angular8/src/app/app.component.ts
import { Component } from '@angular/core';
import { LoadParams } from '@zup-it/beagle-web';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'beagle-automated-tests-angular';
  loadParams: LoadParams;
  queryParams = new URLSearchParams(window.location.search);

  constructor() {
    this.loadParams = {
      path: this.queryParams.get('path') || '/payload.json'
    };
  }
}

// automatedTests/react/src/App.tsx
import React from 'react';
import { BeagleProvider, BeagleRemoteView } from '@zup-it/beagle-react';
import BeagleService from './beagle/beagle-service';

function App() {
  const windowUrl = window.location.search;
  const queryParams = new URLSearchParams(windowUrl);
  const path = queryParams.get("path") || '/payload.json'

  return (
    <BeagleProvider value={BeagleService}>
      <BeagleRemoteView path={path} />
    </BeagleProvider>
  );
}

export default App;
